version: '3.8'

services:
  exec:
    build:
      dockerfile: Dockerfile_dev
      context: .
      tags:
        - 'jointask:exec'
    environment:
      BASE_DIR: '/fixtures/test'
      NUM_USERS: 1000
    volumes:
      - .:/src
      - ./fixtures:/fixtures
    deploy:
      resources:
        limits:
          memory: '512m'
          cpus: '.5'

  db:
    build:
      dockerfile: Dockerfile
      context: db
      tags:
        - 'jointask:db'
    ports:
      - '6432:5432'
    depends_on:
      - exec
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      BASE_DIR: '/fixtures/test'
    volumes:
      - ./fixtures:/fixtures
    deploy:
      resources:
        limits:
          memory: '512m'
          cpus: '.5'
