name: Release

on:
  push:
    branches:
      - "master"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - id: 'checkout'
        name: 'Checkout'
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: '1'

      - id: 'copymd'
        name: 'Copy Md Files to single dir'
        run: |
          mkdir -p .md/fig
          for p in $(ls exercise_*/README.md); do cp ${p} .md/$(dirname ${p}).md; done
          cp exercise_*/fig/* .md/fig/

      - id: 'markdown'
        name: 'Markdown Generation'
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: .md
          output_dir: .md
          build_html: false

      - id: 'release'
        name: 'Release'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Release"
          files: |
            README.md
            LICENSE
            **/*.pdf
