name: Tests

on:
  push:
    branches:
      - "master"
  pull_request:
    types:
      - closed
    branches:
      - "master"
  workflow_dispatch:

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - id: 'checkout'
        name: 'Checkout'
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: '1'

      - id: 'markdown'
        name: 'Markdown Generation'
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: exercise_01
          output_dir: exercise_01
          build_html: false

  release:
    runs-on: ubuntu-latest
    steps:
      - id: 'checkout'
        name: 'Checkout'
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: '1'

      - id: 'release'
        name: 'Release'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Release"
          files: |
            README.md
            LICENSE
