name: Tests

on:
  push:
    branches:
      - "master"
  pull_request:
    types:
      - closed
    branches:
      - "master"
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suffix:
          - '01'
          - '02'
          - '03'
    steps:
      - id: 'checkout'
        name: 'Checkout'
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: '1'
      - id: 'test'
        name: 'test'
        run: cd exercise_${{ matrix.suffix }} && make tests.ci
